#pragma once

#define TILETYPE_NONE 0
#define TILETYPE_AIR 1

#define TILETYPE_DIRT 2
#define TILETYPE_DIRT_ROCK 3
#define TILETYPE_DIRT_OVERHANG 4

#define TILETYPE_SURFACE 5
#define TILETYPE_GRASS 6
#define TILETYPE_GRASS_ROCK1 7
#define TILETYPE_GRASS_ROCK2 8

#define TILETYPE_TREE 9
#define TILETYPE_TREE_PINE 10
#define TILETYPE_TREE_DEAD 11

#define TILETYPE_BRICK 12
#define TILETYPE_DOOR 13
#define TILETYPE_DOOR_OPEN 14
#define TILETYPE_STAIRS_UP 15
#define TILETYPE_STAIRS_DOWN 16
#define TILETYPE_COBWEB 17

#define NUM_TILE_TYPES 18 // Always one more than the last tiletype
